{
 "title": "Requestko",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_requests_in_progress", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(custom_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "CPU on instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Number of noncollectable objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Unhandled Exceptions",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_exceptions_total",
     "legendFormat": "Unhandled exception class: {{exception_type}}"
    }
   ]
  },
  {
   "title": "Number of collected objects in generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "Generation: {{generation}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "Generation: {{generation}}" }
   ]
  }
 ]
}